ptdg59 Finished work
eugeneslab-taiga/foxtrip.web pull request #1
Opened 2021-08-18 14:36 UTC by K3130

I have finished the class, please check.

2021-08-18 19:20 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.h
> +    Tc2web_Translator(QString mlsFile);
Аргументы конструктора и методов лучше передавать по константной ссылке, таким образом вы избежите лишнего копирования

2021-08-18 20:04 UTC, tagiltsev-evgenii requested changes

2021-08-18 20:04 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    stream << str;
Почему не через file.write()?

2021-08-18 20:07 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.h
> +    QByteArray data;
Еще забыл сказать: глобальные переменные для класса принято делать с префиксом "m_"

2021-08-19 05:04 UTC, K3130 commented on src/Tc2web_Translator.h
> +    Tc2web_Translator(QString mlsFile);
Да вы правы, не обратил внимания.

2021-08-19 05:05 UTC, K3130 commented on src/Tc2web_Translator.h
> +    void replaceTranslation(QString key, QString language, QString value);
Понял переделаю.

2021-08-19 05:06 UTC, K3130 commented on src/Tc2web_Translator.h
> +    QByteArray data;
Понял, про m_  не знал.

2021-08-19 05:07 UTC, K3130 commented on src/Tc2web_Translator.cpp
> +Tc2web_Translator::Tc2web_Translator(QString mlsFile) : QObject(nullptr)
Хорошо)

2021-08-19 05:12 UTC, K3130 commented on src/Tc2web_Translator.cpp
> +        return;
Я только в коротких условиях так делаю. Хорошо буду переносить.

2021-08-19 05:16 UTC, K3130 commented on src/Tc2web_Translator.cpp
> +    result.insert("keys", obj);
Суть в том, что я вам говорил раньше. Нет возможности изменять объект который находится внутри другого объекта. Из за этого приходится получать, один объект, из него брать другой, а потом все упаковывать в третий. Либо я не додумал это, но я потратил много часов на это.

2021-08-19 05:18 UTC, K3130 commented on src/Tc2web_Translator.cpp
> +void Tc2web_Translator::appendLanguage(QString key, QString language, QString word)
Слово которое возвращает переводчик. Здесь я добавляю по ключу новую пару на пример ru: "Привет";

2021-08-19 05:20 UTC, K3130 commented on src/Tc2web_Translator.cpp
> +void Tc2web_Translator::removeLanguage(QString key, QString language)
Здесь я удаляю из ключа, язык. то есть пару на пример ru: "Привет". Реализацию удаления языка я не написал т.к хотел узнать сначала о property.

2021-08-19 05:21 UTC, K3130 commented on src/Tc2web_Translator.cpp
> +    stream << str;
Просто сделал такой выбор.

2021-08-19 06:08 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    stream << str;
Ну хорошо. Просто объект file уже создан и вы бы использовали его метод. А так вы создаете еще QTextStream, а перед этим еще конвертируете QByteArray в QString. Все это занимает процессорное время и память

2021-08-19 06:55 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +void Tc2web_Translator::appendLanguage(QString key, QString language, QString word)
> Слово которое возвращает переводчик. Здесь я добавляю по ключу новую пару на пример ru: "Привет";

Не не, данный метод должен добавлять язык в объект _languages_. Добавлять новый язык в ключе можно делать через _replaceTranslation()_ - если такого языка в ключе нет, то необходимо его добавить. Я писал об этом

2021-08-19 06:58 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +void Tc2web_Translator::removeLanguage(QString key, QString language)
> Здесь я удаляю из ключа, язык. то есть пару на пример ru: "Привет". Реализацию удаления языка я не написал т.к хотел узнать сначала о property.

Мм, нет - все таки этот метод должен удалять из списка доступных языков _languages_. А удаление перевода из ключа я пропустил как то. Давайте тогда сделаем метод _removeTranslation()_ где вы эту операцию будете делать

2021-08-19 07:06 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    result.insert("keys", obj);
Я понял. Ну окей, пускай так будет. Только обзовите переменные как нибудь)) Мы же не называем детей "ребенок" и "ребенок1" :)

2021-08-19 15:03 UTC, K3130 commented on src/Tc2web_Translator.cpp
> +    doc = QJsonDocument::fromJson(str.toUtf8());
Да, проблемы с кодировкой решил таким образом.

2021-08-19 15:58 UTC, tagiltsev-evgenii requested changes

2021-08-19 15:58 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    return QString(m_doc.object().value("keys").toObject().value(aKey).toObject().value(aLanguage).toString());
Вот такие конструкции - очень вредные. Они крайне не читабельны. Старайтесь писать код чисто и без усложнений, как будто пишете код для второклашки. Программист после вас скажет вам спасибо)) А вот за это проклянет на всю оставшеюся жизнь

2021-08-19 15:58 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    QJsonObject boxWith;
Box  - тоже не очень удачное название для этой переменной. Какая "коробка"? Что "коробка с..."? тогда это что получается, это объект JSON который описывает какую то коробку?! Имя переменной - часть комментария к коду, оно должно нести смысл. Мне кажется все таки, что m_doc["keys"].toObject() выполняет поиск root компонента в дереве для ключей, поэтому и назвать можно что то типа rootKeysJsonObject. boxWith - это объект ключа, можно обозвать его как то типа keyJsonObject

2021-08-19 15:58 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    QJsonArray langArr = result.value("languages").toArray();
Не бойтесь, буквенных лимитов у вас нет. Лучше назвать немного длиннее, но в меру только: 2-3 коротких слова достаточно. Акронимы - вредная штука. Да, есть устоявшиеся акронимы типа min, max и пр. - с этим нет проблем. В других случаях - лучше избегать акронимов

2021-08-19 15:58 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +            langArr.erase(it);
Хорошо, нашли и удалили. А нужно ли нам после этого продолжать цикл?

2021-08-19 15:58 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    QJsonDocument docs(aObj);
docs? Несколько документов? Хм, ну я то вижу только один

2021-08-19 15:58 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    m_doc = QJsonDocument::fromJson(str.toUtf8());
Могу конечно ошибаться, но QByteArray уже в utf8. Если не пробовали без преобразований написать текст - попробуйте. У меня работает

2021-08-19 15:58 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +    langArr.push_back(aLanguage);
append лучше)) push_back больше из STL библиотеки

2021-08-20 16:54 UTC, tagiltsev-evgenii requested changes

2021-08-20 16:54 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.h
> +    void signalLanguage();
Для свойств лучше называть с окончанием Changed. В нашем случае languageChanged()

2021-08-20 16:54 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +        return;
А если уберете, что изменится?)) Он же практически в конце функции стоит, он все равно закончится в следующей строке

2021-08-20 16:54 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +
Хм. А если в файле есть такой язык, то заменить перевод не получится?

2021-08-21 20:10 UTC, tagiltsev-evgenii commented on src/Tc2web_Translator.cpp
> +}
Лайфхак на будущее: можно не копипастить код, а просто вызвать метод, ибо функционал у них одинаковый. Лучше избегать копипаста, если это можно избежать. 

`
QString Tc2web_Translator::translate(const QString &aKey)
{
   translate(aKey, m_language)
}
`

2021-08-21 20:12 UTC, tagiltsev-evgenii approved these changes

2021-08-21 20:12 UTC, merged