Feature ptdkd7
eugeneslab-taiga/foxtrip.web pull request #2
Opened 2021-08-27 10:16 UTC by K3130

2021-08-29 08:19 UTC, K3130 commented on src/Tc2web_Customizer.h
> +    Q_PROPERTY(WRITE update NOTIFY currentIndexTheme)
Переделал, но тут была проблема. метод update() в задании имеет тип void а в property нужен int. Переделал метод и теперь он возвращает индекс текущей темы.

2021-08-30 15:34 UTC, tagiltsev-evgenii requested changes

2021-08-30 15:34 UTC, tagiltsev-evgenii commented on src/Tc2web_Customizer.h
> +    Q_INVOKABLE int update();
В описании к задаче метод update() ничего не возвращает

2021-08-30 15:34 UTC, tagiltsev-evgenii commented on src/Tc2web_Customizer.h
> +public:
reloadThemes () : Q_INVOKABLE void - метод отсутствует

2021-08-30 15:34 UTC, tagiltsev-evgenii commented on src/Tc2web_Customizer.cpp
> +    QTextStream in(&fileFttm);
QFile так же имеет метод readLine() и atEnd(). Теряется смысл в создании нового объекта - стрима

2021-08-30 15:34 UTC, tagiltsev-evgenii commented on src/Tc2web_Customizer.cpp
> +        if (line[0] != "#")
Я бы так не надеялся что 0 компонент там есть. Что бы перестраховаться, советую проверить line на пустоту

2021-08-30 15:34 UTC, tagiltsev-evgenii commented on src/Tc2web_Customizer.cpp
> +        tempKeyWords.value = tempStringList[2];
Если там не три элемента, то приложение рухнет. Проверьте что там есть все таки три элемента. Если нет, то выдайте qFatal() c текстом: "Web.Customizer: error in line 3 - number of arguments doesn't match with required number."

2021-08-30 15:34 UTC, tagiltsev-evgenii commented on src/Tc2web_Customizer.cpp
> +    QString fullPathToTheme = m_pathToDir + "/themes/" + m_Tc2webThemes.data(m_Tc2webThemes.index(m_Tc2webThemes.defaultTheme(),0),Tc2web_Themes::FileRole).toString();
1. Это в метод reloadThemes() нужно перенести
2. Строку 188 разнесите на разные строки - слишком длинная строка

2021-09-01 09:18 UTC, tagiltsev-evgenii requested changes

2021-09-01 09:57 UTC, K3130 commented on src/Tc2web_Customizer.cpp
> +                readXmlStruct.isDefault = QVariant(QString(attrib.value("default").toString())).toBool();
Да была проблема именно в этом. Тогда поменяем в xml файле на 1,0

2021-09-01 09:57 UTC, K3130 commented on src/main.cpp
> +    Tc2web_Customizer* customizer = new Tc2web_Customizer("c:/Users/smirnov.k/Desktop/Task/build-foxtrip.web-Desktop_Qt_5_15_2_MinGW_64_bit-Debug/debug", nullptr);
Да это тест был)) Забыл стереть.

2021-09-02 06:23 UTC, tagiltsev-evgenii requested changes

2021-09-02 06:23 UTC, tagiltsev-evgenii commented on src/main.cpp
> +    Tc2web_Customizer* customizer = new Tc2web_Customizer(QString(), nullptr);
Сделайте пожалуйста так, что бы если путь пустой, то искать директорию themes рядом с исполняемым файлом

2021-09-02 10:38 UTC, tagiltsev-evgenii approved these changes

2021-09-02 10:38 UTC, merged